openapi: '3.0.0'
info:
  title: Calculator
  description: Arithemtics over HTTP!
  version: '1.0'
servers: 
    - url: http://localhost:8080
      description: Local dev server  
#host: calcapi.cloudapp.net
#basePath: /api
#schemes:
#  - http
paths:
  '/add':
    post:
      description: Responds with a sum of two numbers.
      parameters:
        - name: a
          in: query
          description: First operand.
          required: true
          schema:
            type: integer
            format: int64
        - name: b
          in: query
          description: Second operand.
          required: true
          schema:
            type: integer
            format: int64
      responses: 
        '200':
          description: Sum of operand1 and operand2.
        '401':
          description: Missing operand.
        '402':
          description: Operands are not both numbers.   
        default:
          description: Unexpected error
  '/mult':
    post:
      description: Responds with a product of two numbers.
      parameters:
        - name: a
          in: query
          description: First operand.
          required: true
          schema:
            type: integer
            format: int64
        - name: b
          in: query
          description: Second operand.
          required: true
          schema:
            type: integer
            format: int64
      responses: 
        '200':
          description: Product of operand1 and operand2.
        '401':
          description: Missing operand.
        '402':
          description: Operands are not both numbers.   
        default:
          description: Unexpected error
  '/subtract':
    post:
      description: Responds with a difference between two numbers.
      parameters:
        - name: a
          in: query
          description: First operand.
          required: true
          schema:
            type: integer
            format: int64
        - name: b
          in: query
          description: Second operand.
          required: true
          schema:
            type: integer
            format: int64
      responses: 
        '200':
          description: Difference of operand1 and operand2.
        '401':
          description: Missing operand.
        '402':
          description: Operands are not both numbers.   
        default:
          description: Unexpected error
  '/divide':
    post:
      description: Responds with a quotient of two numbers.
      parameters:
        - name: a
          in: query
          description: First operand.
          required: true
          schema:
            type: integer
            format: int64
        - name: b
          in: query
          description: Second operand.
          required: true
          schema:
            type: integer
            format: int64
      responses: 
        '200':
          description: Quotient of operand1 and operand2.
        '401':
          description: Missing operand.
        '402':
          description: Operands are not both numbers.   
        default:
          description: Unexpected error
    
